### ISSUE TITLE
As a Student Login/Registration page

### ISSUE THREAD

**Issue by foyzulkarim** [foyzulkarim/code-coopers-lms#1]
Student's login page should have also registration feature. so that he/she can do registration if not registered yet. the registration and login boxes should be side by side, NOT up and down

![image](https://user-images.githubusercontent.com/497812/34995995-6a6a3ee2-fb02-11e7-8792-f0e8ed11f0e5.png)

**Comment by ony19161** [comment]
Modified the signin UI, let me know your concerns
<img width="734" alt="newsigninui" src="https://user-images.githubusercontent.com/22003207/35115025-f209dc86-fcb0-11e7-801a-480574504449.PNG">
